Proyecto_201700404/Models/ViewModels/TableroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto_201700404.Models.ViewModels
{
    public class TableroViewModel
    {
        [Required]
        public int Fila { set; get; }

        [Required]
        public int Columna { set; get; }
    }
}

Proyecto_201700404/Controllers/JugarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_201700404.Models;
using Proyecto_201700404.Models.ViewModels;
using Proyecto_201700404.Clases;
using System.IO;
using System.Xml;

namespace Proyecto_201700404.Controllers
{
    public class JugarController : Controller
    {
        // GET: Jugar
        //public static List<Ficha> fichas = new List<Ficha>();
        //public static int turno = 0;
        public ActionResult Jugar()
        {
            return View();
        }
        public FileResult Descargar() {
            string Rutasitio = Server.MapPath("~/");
            string nombreArch = "Archivo"+Variables.N_archivo;
            string rutacompleta = Path.Combine(Rutasitio+"/FilesDes/"+nombreArch+".xml");

            XmlWriter xmlWriter = XmlWriter.Create(rutacompleta);
            xmlWriter.WriteStartDocument();
           
            xmlWriter.WriteStartElement("tablero");
            xmlWriter.WriteString("\r\n\t");

            foreach (var ficha in Variables.fichas)
            {
                xmlWriter.WriteStartElement("ficha");


                xmlWriter.WriteString("\r\n\t\t");
                xmlWriter.WriteStartElement("color");
                xmlWriter.WriteString(ficha.color);
                xmlWriter.WriteEndElement();


                xmlWriter.WriteString("\r\n\t\t");
                xmlWriter.WriteStartElement("columna");
                xmlWriter.WriteString(this.regresarLetra(ficha.columna));
                xmlWriter.WriteEndElement();


                xmlWriter.WriteString("\r\n\t\t");
                xmlWriter.WriteStartElement("fila");
                xmlWriter.WriteString(ficha.fila.ToString());
                xmlWriter.WriteEndElement();

                xmlWriter.WriteString("\r\n\t");



                //xmlWriter.WriteStartElement("");
                //xmlWriter.WriteEndElement(); xmlWriter.WriteStartElement("");
                //xmlWriter.WriteEndElement();

                xmlWriter.WriteEndElement();

            }


            xmlWriter.WriteStartElement("siguienteTiro");

            xmlWriter.WriteStartElement("color");
            xmlWriter.WriteString("\r\n\t\t");
            if (Variables.turno == 1) {
                xmlWriter.WriteString("negro");
            } else if (Variables.turno==2) {
                xmlWriter.WriteString("blanco");
            }
            xmlWriter.WriteEndElement();


            xmlWriter.WriteEndElement();
            xmlWriter.WriteString("\r\n");
            xmlWriter.WriteEndDocument();

            xmlWriter.Close();
            Variables.N_archivo = Variables.N_archivo + 1;


            return File(rutacompleta,"application/xml",nombreArch+".xml");
            //return View();  
        }

        private string regresarLetra(int columna)
        {
            String letra = "";
            switch (columna) {
                case 1:
                    letra = "A";
                    break;
                case 2:
                    letra = "B";
                    break;
                case 3:
                    letra = "C";
                    break;
                case 4:
                    letra = "C";
                    break;
                case 5:
                    letra = "E";
                    break;
                case 6:
                    letra = "F";
                    break;
                case 7:
                    letra = "G";
                    break;
                case 8:
                    letra = "H";
                    break;
                default:
                    break;
            }
            return letra;
           
        }

        public ActionResult Ganador() {
            Ganador ganador = new Ganador();

            int fichasblancas = 0;
            int fichasnegras = 0;
            foreach (var item in Variables.fichas)
            {

                System.Diagnostics.Debug.WriteLine("Ficha color: "+item.color+" fila: "+item.fila+" columna: "+item.columna);
                if (item.color == "blanco") {
                    fichasblancas = fichasblancas + 1;
                } else if (item.color=="negro") {
                    fichasnegras = fichasnegras + 1;
                
                }

            }

            
            System.Diagnostics.Debug.WriteLine("Fichas blancas: " +fichasblancas);
            System.Diagnostics.Debug.WriteLine("Fichas negras:  "+fichasnegras);
            int fb = 0;
            int fn = 0;
                
            foreach (var item in Variables.fichas)
            {
                if (item.color=="blanco") {
                    fb = fb + 1;
                }

            }
            foreach (var item in Variables.fichas)
            {
                if (item.color == "negro")
                {
                    fn = fn + 1;
                }

            }

            System.Diagnostics.Debug.WriteLine("OTRO RESULTADO Fichas blancas: " + fb);
            System.Diagnostics.Debug.WriteLine("OTRO RESULTADO Fichas negras:  " + fn);

            var gan = (Proyecto_201700404.Models.USUARIO)Session["user"];
            if (fichasblancas > fichasnegras)
            {
                if (Variables.modalidad == 1) {

                    if (Variables.viene == 1)
                    {
                        ganador.ganador = "Invitado";
                    }
                    else
                    {
                        ganador.ganador = "Maquina";
                    }
                    ganador.perdedor = gan.nombreUsuario;
                    ganador.fichasGanador = fichasblancas;
                    ganador.fichasPerdedor = fichasnegras;


                    ganador.movimientosGanador = Variables.mov_jugador2;
                    ganador.movimeintoPerdedor = Variables.mov_jugador1;

                } else if (Variables.modalidad==2) {

                    if (Variables.viene == 1)
                    {
                        ganador.perdedor = "Invitado";
                    }
                    else
                    {
                        ganador.perdedor = "Maquina";
                    }
                    ganador.ganador = gan.nombreUsuario;
                    ganador.fichasGanador = fichasnegras;
                    ganador.fichasPerdedor = fichasblancas;


                    ganador.movimientosGanador = Variables.mov_jugador1;
                    ganador.movimeintoPerdedor = Variables.mov_jugador2;

                }

                //ganador.ganador = gan.nombreUsuario;
                
                //ganador.perdedor = gan.nombreUsuario; COMENTADO POR LA NUEVA MODALIDAD DE JUEGO
                //ganador.fichasGanador = fichasblancas ;
                //ganador.fichasPerdedor = fichasnegras;

                
                //ganador.movimientosGanador = Variables.mov_jugador2;
                //ganador.movimeintoPerdedor = Variables.mov_jugador1;


            }
            else if (fichasnegras > fichasblancas)
            {

                if (Variables.modalidad == 1)
                {
                    ganador.ganador = gan.nombreUsuario;
                    if (Variables.viene == 1)
                    {
                        ganador.perdedor = "Invitado";
                    }
                    else
                    {
                        ganador.perdedor = "Maquina";
                    }

                    ganador.fichasGanador = fichasnegras;
                    ganador.fichasPerdedor = fichasblancas;
                    ganador.movimientosGanador = Variables.mov_jugador1;
                    ganador.movimeintoPerdedor = Variables.mov_jugador2;


                }
                else if(Variables.modalidad==2) {

                    ganador.perdedor = gan.nombreUsuario;
                    if (Variables.viene == 1)
                    {
                        ganador.ganador = "Invitado";
                    }
                    else
                    {
                        ganador.ganador = "Maquina";
                    }

                    ganador.fichasGanador = fichasblancas;
                    ganador.fichasPerdedor = fichasnegras;
                    ganador.movimientosGanador = Variables.mov_jugador2;
                    ganador.movimeintoPerdedor = Variables.mov_jugador1;


                }

                
            }
            else if (fichasnegras==fichasblancas) {
                ganador.ganador = "Empate";
                ganador.perdedor = "Invitado";
                ganador.fichasGanador = fichasnegras;
                ganador.fichasPerdedor = fichasblancas;
                ganador.movimientosGanador = Variables.mov_jugador1;
                ganador.movimeintoPerdedor = Variables.mov_jugador2;
            }

            System.Diagnostics.Debug.WriteLine("ESTOS DATOS TRAE LA VARIABLE GANADOR fichas ganador: "+ganador.fichasGanador);
            System.Diagnostics.Debug.WriteLine("ESTOS DATOS TRAE LA VARIABLE GANADOR fichas perdedor: " + ganador.fichasPerdedor);




           Variables.ganador = ganador;

            Variables.fichas.Clear();
            Variables.VaciarTablero();



            iGamegtEntities1 bdatos = new iGamegtEntities1();

            Juego juego = new Juego();
            juego.idjugador = gan.id_usuario;
            juego.ganador = Variables.ganador.ganador;
            juego.perdedor = Variables.ganador.perdedor;
            juego.mov_ganador = Variables.ganador.movimientosGanador;
            juego.mov_perdedor = Variables.ganador.movimeintoPerdedor;
            juego.fichas_ganador = Variables.ganador.fichasGanador;
            juego.fichas_perdedor = Variables.ganador.fichasPerdedor;

            bdatos.Juego.Add(juego);
            bdatos.SaveChanges();



            return View();
        }

        public ActionResult RegresarMenu() {
            return RedirectToAction("Player","Player");
        }

Proyecto_201700404/Controllers/JugarXtremeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_201700404.Clases;
using Proyecto_201700404.Models;

namespace Proyecto_201700404.Controllers
{
    public class JugarXtremeController : Controller
    {
        // GET: JugarXtreme
        public ActionResult Jugar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Jugar(string idcelda) {
            if (idcelda == "tablero" || idcelda == null)
            {
                //System.Diagnostics.Debug.WriteLine("SIGUE PASANDO ACA ESTA COCHINADA");
            }
            else {
                char sep = '-';

                string[] datos = idcelda.Split(sep);
                int fil = int.Parse(datos[0]);
                int colum = int.Parse(datos[1]);

                //System.Diagnostics.Debug.WriteLine("FILA: "+fil+"  COLUMNA:  "+colum);
                Variables.partida.PonerFicha(fil,colum);   
            }

            Validar validar = new Validar(Variables.partida.getListaFichas(),Variables.partida.getFilasTablero(),Variables.partida.getColumnasTabler());
            validar.Buscar(1);
            Validar validacion = new Validar(Variables.partida.getListaFichas(), Variables.partida.getFilasTablero(), Variables.partida.getColumnasTabler());
            validacion.Buscar(2);

            if (validar.listadePosibilidades().Count()==0 && validacion.listadePosibilidades().Count()==0) {
                Variables.Se_termino = 1;
            }


            return PartialView("Tablero");
            
        }

        public ActionResult verGanador() {
            Ganador ganador = new Ganador();

            int fichaslocal = 0;
            int fichasinvitado = 0;
            foreach (var item in Variables.partida.getListaFichas())
            {
                if (item.Turnodueño == 1)
                {
                    fichaslocal = fichaslocal + 1;
                }
                else {
                    fichasinvitado = fichasinvitado + 1;
                }

            }

            if (fichaslocal > fichasinvitado)
            {
                ganador.ganador = Variables.partida.JugadorLocal().Alias;
                ganador.fichasGanador = fichaslocal;
                ganador.perdedor = Variables.partida.JugadorInvitado().Alias;
                ganador.fichasPerdedor = fichasinvitado;
                ganador.movimientosGanador = Variables.partida.JugadorLocal().getMovimientos();
                ganador.movimeintoPerdedor = Variables.partida.JugadorInvitado().getMovimientos();
            }
            else if (fichasinvitado > fichaslocal)
            {
                ganador.ganador = Variables.partida.JugadorInvitado().Alias;
                ganador.fichasGanador = fichasinvitado;
                ganador.perdedor = Variables.partida.JugadorLocal().Alias;
                ganador.fichasPerdedor = fichaslocal;
                ganador.movimientosGanador = Variables.partida.JugadorInvitado().getMovimientos();
                ganador.movimeintoPerdedor = Variables.partida.JugadorLocal().getMovimientos();

            }
            else {
                ganador.ganador = "EMPATE";
                ganador.fichasGanador = fichasinvitado;
                ganador.perdedor = Variables.partida.JugadorLocal().Alias;
                ganador.fichasPerdedor = fichaslocal;
                ganador.movimientosGanador = Variables.partida.JugadorLocal().getMovimientos();
                ganador.movimeintoPerdedor = Variables.partida.JugadorInvitado().getMovimientos();

            }

            var gan = (Proyecto_201700404.Models.USUARIO)Session["user"];

            Variables.ganador = ganador;


            iGamegtEntities1 bdatos = new iGamegtEntities1();

            Juego juego = new Juego();
            juego.idjugador = gan.id_usuario;
            juego.ganador = Variables.ganador.ganador;
            juego.perdedor = Variables.ganador.perdedor;
            juego.mov_ganador = Variables.ganador.movimientosGanador;
            juego.mov_perdedor = Variables.ganador.movimeintoPerdedor;
            juego.fichas_ganador = Variables.ganador.fichasGanador;
            juego.fichas_perdedor = Variables.ganador.fichasPerdedor;

            bdatos.Juego.Add(juego);
            bdatos.SaveChanges();
            Variables.partida.IniciarPartida();

            return View();
        }


    }
}

Proyecto_201700404/Views/JugarXtreme/Jugar.cshtml
@using Proyecto_201700404.Clases

@{
    

    Layout = null;
    Partida partida = Proyecto_201700404.Clases.Variables.partida;

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Xtreme</title>
    <link href="~/Content/Tablerocss.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
</head>
<body class="variable">

    @using (Ajax.BeginForm("Xtreme", "Xtreme", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "tablero_juego" }))
    {

        <nav class="navbar navbar-expand-lg navbar-light ">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">


                        <li class="nav-item ">
                            <a class="nav-link active text-white btn btn-danger" href="#" tabindex="-1" aria-disabled="true">Iniciar Juego</a>
                        </li>

                    </ul>

                    <form class="form-inline my-2 my-lg-0">
                        <button class="btn btn-danger my-2 my-sm-0 btn-lg">@Html.ActionLink("Subir", "Archivo", "Archivo", new { area = "" }, new { @class = " text-white" })</button>

                        <button class="btn btn-warning my-2 my-sm-0 btn-lg">@Html.ActionLink("Descargar", "Descargar", "Jugar", new { area = "" }, new { @class = " text-white" })</button>
                        <button class="btn btn-dark my-2 my-sm-0 btn-lg">@Html.ActionLink("Regresar", "Regresar", "Jugar", new { area = "" }, new { @class = " text-white" })</button>


                    </form>
                </div>


            </div>


        </nav>
        <div class="container">
            <div class="row justify-content-md-center">
                <div style="background-color:rgba(128, 128, 128,.4);border-radius:10px;" class="col">
                    <label style=" font-family:'Agency FB';font-size:25px;" class="row justify-content-md-center text-white">@partida.JugadorLocal().Alias</label>

                    <div class="row justify-content-md-center">
                        @foreach (var ficha in partida.JugadorLocal().MisFichas())
                        {
                            <div style="width:60px;height:60px;" class="bg-orange">
                                <button style="height:100%;width:100%;border-radius:100%;border-color:white;" class="@ficha.clase"></button>

                            </div>


                        }
                    </div>

                </div>
                <div class="col">
                    <div style="background-color:rgba(128, 128, 128,.9);border-radius:10px ;" class="col">
                        <label style=" font-family:'Agency FB';font-size:25px;" class="row justify-content-md-center text-white">@partida.JugadorInvitado().Alias</label>

                        <div class="row justify-content-md-center">
                            @foreach (var ficha in partida.JugadorInvitado().MisFichas())
                            {
                                <div style="width:60px;height:60px;" class="bg-orange">
                                    <button style="height:100%;width:100%;border-radius:100%;border-color:white;" class="@ficha.clase"></button>

                                </div>


                            }

                        </div>


                    </div>

                </div>

            </div>

        </div>



    }

    <div id="tablero_juego">
        @Html.Partial("Tablero")

    </div>
    @Scripts.Render("~/bundles/ajax")

</body>
</html>

Proyecto_201700404/Views/JugarXtreme/Tablero.cshtml
@using Proyecto_201700404.Clases



@{
    Partida partida = Proyecto_201700404.Clases.Variables.partida;
    int altura = 100 / (partida.getColumnasTabler() + 2);
    
}
<div class="container">
    <div class="row" id="tablero">
        <div class="col-2">
            <table class="table table-sm table-dark">
                <thead>
                    <tr>
                        <th scope="col">Movimientos</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>
                            @partida.JugadorLocal().Alias :
                        </th>
                        <th>@partida.JugadorLocal().getMovimientos()</th>
                    </tr>
                    <tr>
                        <th>
                            @partida.JugadorInvitado().Alias :
                        </th>
                        <th>@partida.JugadorInvitado().getMovimientos()</th>
                    </tr>
                    <tr>
                        <th>
                            Valides de la Jugada
                        </th>

                    </tr>

                    <tr>

                        @if (Variables.valides == 0)
                        {
                            <th>
                                Aun no empieza la partida
                            </th>

                        }
                        else if (Variables.valides == 1)
                        {
                            <th>
                                La jugada es valida @Variables.validesde
                            </th>
                        }
                        else if (Variables.valides == 2)
                        {
                            <th>
                                La jugada es invalida @Variables.validesde
                            </th>

                        }


                    </tr>

                </tbody>

            </table>








            <div style="height:20%; border-radius:5px;" class="bg-dark">
                <div class="row  justify-content-md-center">
                    <label style=" font-family:'Agency FB';font-size:50px;" class="text-white">Turno de:</label>
                </div>
                <div class="row justify-content-md-center ">
                    <p style=" font-family:'Agency FB';font-size:30px;" class="text-white">
                        @if (partida.getTurno() == 1)
                        {
                            <label>@partida.JugadorLocal().Alias</label>
                        }
                        else
                        {
                            <label>@partida.JugadorInvitado().Alias</label>
                        }



                    </p>
                </div>
                @*<div class="row justify-content-md-center  ">
                    <div style="width:50%; height:85px;" class="btn btn-success border">
                        @if (partida.getTurno() == 1)
                        {
                            <button style="height:100%;width:100%; border-radius:100%;" class="@partida.JugadorLocal().getFichaTurno().clase"></button>

                          


                        }
                        else
                        {
                            <button style="height:100%;width:100%; border-radius:100%;" class="@partida.JugadorInvitado().getFichaTurno().clase"></button>



                        }
                    </div>
                </div>*@

            </div>
            @if (Proyecto_201700404.Clases.Variables.Se_termino == 1)
            {

                using (Html.BeginForm("verGanador", "JugarXtreme", FormMethod.Post))
                {
                    <div class="form-group row">
                        <button value="Ir a partida" type="submit" class="form-control btn btn-primary">
                            Revelar al ganador  <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
                            </svg>
                        </button>

                    </div>
                }


               

            }





        </div>
        <div class="col-9">
            <div @*class="cuadrojuego"*@>
                <div class="row">

                    @if (partida.getColumnasTabler() < 7)
                    {

                        <style>
                            .alto {
                                height: 85px;
                            }
                        </style>

                    }
                    else if (partida.getColumnasTabler() > 6 && partida.getColumnasTabler() < 10)
                    {
                        <style>
                            .alto {
                                height: 65px;
                            }
                        </style>
                    }
                    else if (partida.getColumnasTabler() > 9 && partida.getColumnasTabler() < 14)
                    {
                        <style>
                            .alto {
                                height: 55px;
                            }
                        </style>
                    }
                    else if (partida.getColumnasTabler() > 13 && partida.getColumnasTabler() < 17)
                    {
                        <style>
                            .alto {
                                height: 45px;
                            }
                        </style>
                    }
                    else if (partida.getColumnasTabler() > 16 && partida.getColumnasTabler() < 21)
                    {
                        <style>
                            .alto {
                                height: 30px;
                            }
                        </style>
                    }

                    <style>
                        .ficha {
                            height: 100%;
                            width: 100%;
                            border-radius: 100% !important;
                            border-color: white;
                        }   
                    </style>



                    @for (int fil = 0; fil < partida.getFilasTablero() + 2; fil++)
                    {
                        for (int col = 0; col < partida.getColumnasTabler() + 2; col++)
                        {


                            if (fil == 0 && col > 0 && col < partida.getColumnasTabler() + 1)
                            {
                                <div style="height:@altura vh;" class="col btn btn-dark border alto">@letra(col)</div>
                            }
                            else if (fil == partida.getFilasTablero() + 1 && col > 0 && col < partida.getColumnasTabler() + 1)
                            {
                                <div style="height:@altura vh;" class="col btn btn-dark border alto">@letra(col)</div>
                            }
                            else if (col == 0 && fil > 0 && fil < partida.getFilasTablero() + 1)
                            {
                                <div style="height:@altura vh;" class="col btn btn-dark border alto">@fil</div>
                            }
                            else if (col == partida.getColumnasTabler() + 1 && fil > 0 && fil < partida.getFilasTablero() + 1)
                            {
                                <div style="height:@altura vh;" class="col btn btn-dark border alto">@fil</div>
                            }
                            else if (fil == 0)
                            {
                                if (col == 0 | col == partida.getColumnasTabler() + 1)
                                {
                                    <div style="height:@altura vh;" class="col btn btn-dark border alto"></div>
                                }
                            }
                            else if (fil == partida.getFilasTablero() + 1)
                            {
                                if (col == 0 | col == partida.getColumnasTabler() + 1)
                                {
                                    <div style="height:@altura vh;" class="col btn btn-dark border alto"></div>
                                }
                            }
                            else
                            {
                            <div style="height:@altura  vh;" class="col btn btn-success border " id="@fil.ToString()-@col.ToString()">
                                @foreach (var item in partida.getListaFichas())
                                {
                                    if (item.fila == fil && item.columna == col)
                                    {
                                        <button class="ficha @item.clase"></button>

                                    }

                                }
                            </div>
                            }


                 



                        }
                        <div class="w-100"></div>
                    }

                </div>
            </div>


        </div>
        <div class="col-1">


        </div>

    </div>

</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    $("#tablero div ").on("click", function (event) {
        var divId = $(this).attr("id");

        $.ajax({
            url: "@Url.Action("Jugar")",
            type: "Post",
            data: { idcelda: divId },
            success: function (data) {
                $("#tablero").html(data);
            }
        }
        );
    });

</script>


@{

    string letra(int col)
    {
        string l = "";
        switch (col)
        {
            case 1:
                l = "A";
                break;
            case 2:
                l = "B";
                break;
            case 3:
                l = "C";
                break;
            case 4:
                l = "D";
                break;
            case 5:
                l = "E";
                break;
            case 6:
                l = "F";
                break;
            case 7:
                l = "G";
                break;
            case 8:
                l = "H";
                break;
            case 9:
                l = "I";
                break;
            case 10:
                l = "J";
                break;
            case 11:
                l = "K";
                break;
            case 12:
                l = "L";
                break;
            case 13:
                l = "M";
                break;
            case 14:
                l = "N";
                break;
            case 15:
                l = "O";
                break;
            case 16:
                l = "P";
                break;
            case 17:
                l = "Q";
                break;
            case 18:
                l = "R";
                break;
            case 19:
                l = "S";
                break;
            case 20:
                l = "T";
                break;
            case 21:
                l = "U";
                break;

        }

        return l;

    }
}