Proyecto_201700404/Models/ViewModels/TableroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto_201700404.Models.ViewModels
{
    public class TableroViewModel
    {
        [Required]
        public int Fila { set; get; }

        [Required]
        public int Columna { set; get; }
    }
}

Proyecto_201700404/Controllers/XtremeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_201700404.Models.ViewModels;
using Proyecto_201700404.Models;
using Proyecto_201700404.Clases;

namespace Proyecto_201700404.Controllers
{
    public class XtremeController : Controller
    {
        // GET: Xtreme
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RegistroInvitado() {
            return View();
        }
        [HttpPost]
        public ActionResult RegistroInvitado(InvitadoViewModel invitado) {
            
            if (ModelState.IsValid)
            {
                //System.Diagnostics.Debug.WriteLine(invitado.nombre);
                Variables.partida.IniciarPartida();
                
                Proyecto_201700404.Models.USUARIO user = (Proyecto_201700404.Models.USUARIO)Session["user"];
               
                Jugador contrincante = new Jugador();//el usuario invitado
             
                //Se agregan a los dos jugadores a la partida
                Variables.partida.JugadorLocal().Alias=user.nombreUsuario;
                Variables.partida.JugadorInvitado().Alias = invitado.nombre;


                return RedirectToAction("RegistroFichas");
            }
            else {
                return View();
            }
            
        }
        public ActionResult RegistroFichas() {
            return View();
        }
        [HttpPost]
        public ActionResult FichasHost(ColorFichaViewModel colorficha) {
            if (ModelState.IsValid)
            {
                iGamegtEntities1 db = new iGamegtEntities1();

                var col = (from d in db.ColorFicha where d.idcolor == colorficha.idcolor select d).FirstOrDefault();

                Ficha ficha = new Ficha();
                ficha.color = col.color;
                ficha.clase = col.clase;
                int repetido = 0;
                if (Variables.partida.JugadorLocal().puedoAgregarfichas() == true && Variables.partida.JugadorLocal().fichaRepetida(ficha) != true)
                {
                    //si su lista es menor a 5 y que el color no sea repetido
                    foreach (var fichacontrincante in Variables.partida.JugadorInvitado().MisFichas())
                    {
                        if (fichacontrincante.color == ficha.color)
                        {
                            repetido = 1;
                        }

                    }
                    if (repetido == 0)
                    {
                        ficha.Turnodueño = 1;
                        Variables.partida.JugadorLocal().MisFichas().Add(ficha);
                    }



                }
                return RedirectToAction("RegistroFichas");

            }
            else {
                return RedirectToAction("RegistroFichas");
            }
            
            //System.Diagnostics.Debug.WriteLine("LAS FICHAS DEL JUGADOR LOCAL");

            //foreach (var item in Variables.partida.JugadorLocal().MisFichas())
            //{
            //    System.Diagnostics.Debug.WriteLine("color: "+item.color+"  clase: "+item.clase);

            //}

            //System.Diagnostics.Debug.WriteLine("COLORES DE HOST  "+col.color+" clase: "+col.clase);
           
        }
        [HttpPost]
        public ActionResult FichasInvitado(ColorFichaViewModel colorficha)
        {

            if (ModelState.IsValid)
            {
                iGamegtEntities1 db = new iGamegtEntities1();

                var col = (from d in db.ColorFicha where d.idcolor == colorficha.idcolor select d).FirstOrDefault();

                Ficha ficha = new Ficha();
                ficha.color = col.color;
                ficha.clase = col.clase;
                int repetido = 0;
                if (Variables.partida.JugadorInvitado().puedoAgregarfichas() == true && Variables.partida.JugadorInvitado().fichaRepetida(ficha) != true)
                {
                    foreach (var fichacontrincante in Variables.partida.JugadorLocal().MisFichas())
                    {
                        if (fichacontrincante.color == ficha.color)
                        {
                            repetido = 1;
                        }

                    }
                    if (repetido == 0)
                    {
                        ficha.Turnodueño = 2;

                        Variables.partida.JugadorInvitado().MisFichas().Add(ficha);
                    }
                }
                return RedirectToAction("RegistroFichas");

            }
            else {
                return RedirectToAction("RegistroFichas");
            }   
           
        }


        public ActionResult Requisitos() {
            if (Variables.partida.JugadorInvitado().MisFichas().Count() != 0 && Variables.partida.JugadorLocal().MisFichas().Count() != 0)
            {
                return RedirectToAction("ConfiguracionTablero");
            }
            else {
                return RedirectToAction("RegistroFichas");
            }
        }




        public ActionResult ConfiguracionTablero() {
            return View();
        }




        [HttpPost]
        public ActionResult ConfiguracionTablero(TableroViewModel tablero) {
            if (ModelState.IsValid)
            {
                Variables.partida.IniciarTablero(tablero.Fila,tablero.Columna);
                return RedirectToAction("Jugar","JugarXtreme");
            }
            else {
                return View();
            }
            
        }





       
       
        public ActionResult Xtreme() {
            return View();
        }
        
       
    }
}

Proyecto_201700404/Views/Xtreme/ConfiguracionTablero.cshtml
@model Proyecto_201700404.Models.ViewModels.TableroViewModel
@{
    ViewBag.Title = "ConfiguracionTablero";
    Layout = "~/Views/Master/CampodeJuego.cshtml";
}

@using (Html.BeginForm("ConfiguracionTablero", "Xtreme", FormMethod.Post))
{
    <div style="border-radius:10px; width:600px; height:50%; position:absolute; top:60%; left:50%; transform:translate(-47%,-50%); background-color:rgba(0, 0, 0,.8)">
        <style>
            .blanco {
                color: white;
            }
        </style>
        <div style="margin-left: 50%; position: absolute; margin-top: 25%; width: 50%; height: 80%; transform: translate(-50%,-50%);" class="">
            <p style=" font-family:'Agency FB';font-size:25px; " class="text-center text-white">
                Elija las configuraciones del tablero.

            </p>

            <div class="form-group row">

                <label class="col-sm-5 col-form-label text-white">No. Filas</label>
                <div class="col-sm-7">
                    @Html.TextBoxFor(d => d.Fila, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Fila, null, new { @class = "blanco" })


                </div>
            </div>

            <div class="form-group row">

                <label class="col-sm-5 col-form-label text-white">No. Columnas</label>
                <div class="col-sm-7">
                    @Html.TextBoxFor(d => d.Columna, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Columna, null, new { @class = "blanco" })


                </div>
            </div>

            <div class="form-group row">
                <button value="Ir a partida" type="submit" class="form-control btn btn-primary">
                    Ir a Tablero   <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
                    </svg>
                </button>

            </div>
        </div>


    </div>
}

Proyecto_201700404/Views/Xtreme/RegistroFichas.cshtml
@model Proyecto_201700404.Models.ViewModels.ColorFichaViewModel
@using Proyecto_201700404.Models
@using Proyecto_201700404.Clases
@{
    ViewBag.Title = "RegistroFichas";
    Layout = "~/Views/Master/CampodeJuego.cshtml";
    iGamegtEntities1 db = new iGamegtEntities1();
    Partida partida = Variables.partida;
}



    <div style="border-radius:10px; width:600px; height:50%; position:absolute; top:60%; left:50%; transform:translate(-47%,-50%);">
        <div style="margin-left: 50%; position: absolute; margin-top: 25%; width: 50%; height: 80%; transform: translate(-50%,-50%);" class="">
            <p style=" font-family:'Agency FB';font-size:25px; " class="text-center text-white">
                Cada jugador podra elegir máximo 5 colores de fichas y mínimo 1.

            </p>
            <br />
            <label style="background-color:rgba(0, 0, 0,.9);border-radius:5px; font-family:'Agency FB';font-size:25px; " class="text-center text-white">@partida.JugadorLocal().Alias</label>
            @using (Html.BeginForm("FichasHost", "Xtreme", FormMethod.Post))
            {
                <div class="form-group row">
                    @Html.DropDownListFor(d => d.idcolor, new SelectList(db.ColorFicha, "idcolor", "color"), "Selecione color", new { @class = " col-sm-8 form-control" })
                    <div class="col-sm-4">
                        <button value="Ir a partida" type="submit" class="form-control btn btn-primary">Elegir</button>

                    </div>

                </div>


            }
            @if (partida.JugadorLocal().MisFichas().Count() != 0)
            {
                <div class="row justify-content-md-center">
                    @foreach (var ficha in partida.JugadorLocal().MisFichas())
                    {
                        <div style="width:60px;height:60px;" class="bg-orange">
                            <button style="height:100%;width:100%;border-radius:100%;border-color:white;" class="@ficha.clase"></button>

                        </div>


                    }

                </div>
                <br />
            }



            <label style=" background-color:rgba(0, 0, 0,.9);border-radius:5px;  font-family:'Agency FB';font-size:25px; " class="text-center text-white">@partida.JugadorInvitado().Alias</label>
            @using (Html.BeginForm("FichasInvitado", "Xtreme", FormMethod.Post))
            {
                <div class="form-group row">
                    @Html.DropDownListFor(d => d.idcolor, new SelectList(db.ColorFicha, "idcolor", "color"), "Selecione color", new { @class = " col-sm-8 form-control" })
                    <div class="col-sm-4">
                        <button value="Ir a partida" type="submit" class="form-control btn btn-primary">Elegir</button>

                    </div>

                </div>


            }
            @if (partida.JugadorInvitado().MisFichas().Count() != 0)
            {
                <div class="row justify-content-md-center">
                    @foreach (var ficha in partida.JugadorInvitado().MisFichas())
                    {
                        <div style="width:60px;height:60px;" class="bg-orange">
                            <button style="height:100%;width:100%;border-radius:100%;border-color:white;" class="@ficha.clase"></button>

                        </div>


                    }

                </div>
                <br />
            }

            @using (Html.BeginForm("Requisitos", "Xtreme", FormMethod.Post))
            {
                <div class="form-group row">
                    <button value="Ir a partida" type="submit" class="form-control btn btn-primary">
                        Ir a partida   <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
                        </svg>
                    </button>

                </div>
            }


        </div>

    </div>

Proyecto_201700404/Views/Xtreme/RegistroInvitado.cshtml
@model Proyecto_201700404.Models.ViewModels.InvitadoViewModel
@{
    ViewBag.Title = "RegistroInvitado";
    Layout = "~/Views/Master/CampodeJuego.cshtml";
}

@using (Html.BeginForm("RegistroInvitado", "Xtreme", FormMethod.Post))
{
    <div style="border-radius:10px; width:600px; height:50%; position:absolute; top:60%; left:50%; transform:translate(-47%,-50%); background-color:rgba(0, 0, 0,.8)">
        <style>
            .blanco {
                color: white;
            }
        </style>
        <div style="margin-left: 50%; position: absolute; margin-top: 25%; width: 50%; height: 80%; transform: translate(-50%,-50%);" class="">
            <p style=" font-family:'Agency FB';font-size:25px; " class="text-center text-white">
                Debe de registrar el nombre del jugador invitado.

            </p>

            <div class="form-group row">

                <label class="col-sm-3 col-form-label text-white">Invitado:</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(d => d.nombre, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.nombre, null, new { @class = "blanco" })


                </div>
            </div>
            <div class="form-group row">
                <button value="Ir a partida" type="submit" class="form-control btn btn-primary">
                    Continuar   <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
                    </svg>
                </button>

            </div>
        </div>


    </div>
}

Proyecto_201700404/Views/Xtreme/Tablero.cshtml
<p>TODAVIA NO TIENE NI DROGA
    </p>

Proyecto_201700404/Views/Xtreme/Xtreme.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Xtreme</title>
    <link href="~/Content/Tablerocss.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
</head>
<body class="variable">

    @using (Ajax.BeginForm("Xtreme", "Xtreme", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "tablero_juego" }))
    {

        <nav class="navbar navbar-expand-lg navbar-light ">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">


                        <li class="nav-item ">
                            <a class="nav-link active text-white btn btn-danger" href="#" tabindex="-1" aria-disabled="true">Iniciar Juego</a>
                        </li>

                    </ul>

                    <form class="form-inline my-2 my-lg-0">
                        <button class="btn btn-danger my-2 my-sm-0 btn-lg">@Html.ActionLink("Subir", "Archivo", "Archivo", new { area = "" }, new { @class = " text-white" })</button>

                        <button class="btn btn-warning my-2 my-sm-0 btn-lg">@Html.ActionLink("Descargar", "Descargar", "Jugar", new { area = "" }, new { @class = " text-white" })</button>
                        <button class="btn btn-dark my-2 my-sm-0 btn-lg">@Html.ActionLink("Regresar", "Regresar", "Jugar", new { area = "" }, new { @class = " text-white" })</button>


                    </form>
                </div>


            </div>


        </nav>



    }

    <div id="tablero_juego">
        @Html.Partial("Tablero")

    </div>
    @Scripts.Render("~/bundles/ajax")

</body>
</html>