Proyecto_201700404/Models/ViewModels/TableroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto_201700404.Models.ViewModels
{
    public class TableroViewModel
    {
        [Required]
        public int Fila { set; get; }

        [Required]
        public int Columna { set; get; }
    }
}

Proyecto_201700404/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_201700404.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Admin()
        {
            return View();
        }
        public ActionResult Cerrar() {
            Session["user"] = null;
            return RedirectToAction("Home","Home");
        }
    }
}

Proyecto_201700404/Controllers/JugarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_201700404.Models;
using Proyecto_201700404.Models.ViewModels;
using Proyecto_201700404.Clases;
using System.IO;
using System.Xml;

namespace Proyecto_201700404.Controllers
{
    public class JugarController : Controller
    {
        // GET: Jugar
        //public static List<Ficha> fichas = new List<Ficha>();
        //public static int turno = 0;
        public ActionResult Jugar()
        {
            return View();
        }
        public FileResult Descargar() {
            string Rutasitio = Server.MapPath("~/");
            string nombreArch = "Archivo"+Variables.N_archivo;
            string rutacompleta = Path.Combine(Rutasitio+"/FilesDes/"+nombreArch+".xml");

            XmlWriter xmlWriter = XmlWriter.Create(rutacompleta);
            xmlWriter.WriteStartDocument();
           
            xmlWriter.WriteStartElement("tablero");
            xmlWriter.WriteString("\r\n\t");

            foreach (var ficha in Variables.fichas)
            {
                xmlWriter.WriteStartElement("ficha");


                xmlWriter.WriteString("\r\n\t\t");
                xmlWriter.WriteStartElement("color");
                xmlWriter.WriteString(ficha.color);
                xmlWriter.WriteEndElement();


                xmlWriter.WriteString("\r\n\t\t");
                xmlWriter.WriteStartElement("columna");
                xmlWriter.WriteString(this.regresarLetra(ficha.columna));
                xmlWriter.WriteEndElement();


                xmlWriter.WriteString("\r\n\t\t");
                xmlWriter.WriteStartElement("fila");
                xmlWriter.WriteString(ficha.fila.ToString());
                xmlWriter.WriteEndElement();

                xmlWriter.WriteString("\r\n\t");



                //xmlWriter.WriteStartElement("");
                //xmlWriter.WriteEndElement(); xmlWriter.WriteStartElement("");
                //xmlWriter.WriteEndElement();

                xmlWriter.WriteEndElement();

            }


            xmlWriter.WriteStartElement("siguienteTiro");

            xmlWriter.WriteStartElement("color");
            xmlWriter.WriteString("\r\n\t\t");
            if (Variables.turno == 1) {
                xmlWriter.WriteString("negro");
            } else if (Variables.turno==2) {
                xmlWriter.WriteString("blanco");
            }
            xmlWriter.WriteEndElement();


            xmlWriter.WriteEndElement();
            xmlWriter.WriteString("\r\n");
            xmlWriter.WriteEndDocument();

            xmlWriter.Close();
            Variables.N_archivo = Variables.N_archivo + 1;


            return File(rutacompleta,"application/xml",nombreArch+".xml");
            //return View();  
        }

        private string regresarLetra(int columna)
        {
            String letra = "";
            switch (columna) {
                case 1:
                    letra = "A";
                    break;
                case 2:
                    letra = "B";
                    break;
                case 3:
                    letra = "C";
                    break;
                case 4:
                    letra = "C";
                    break;
                case 5:
                    letra = "E";
                    break;
                case 6:
                    letra = "F";
                    break;
                case 7:
                    letra = "G";
                    break;
                case 8:
                    letra = "H";
                    break;
                default:
                    break;
            }
            return letra;
           
        }

        public ActionResult Ganador() {
            Ganador ganador = new Ganador();

            int fichasblancas = 0;
            int fichasnegras = 0;
            foreach (var item in Variables.fichas)
            {

                System.Diagnostics.Debug.WriteLine("Ficha color: "+item.color+" fila: "+item.fila+" columna: "+item.columna);
                if (item.color == "blanco") {
                    fichasblancas = fichasblancas + 1;
                } else if (item.color=="negro") {
                    fichasnegras = fichasnegras + 1;
                
                }

            }

            
            System.Diagnostics.Debug.WriteLine("Fichas blancas: " +fichasblancas);
            System.Diagnostics.Debug.WriteLine("Fichas negras:  "+fichasnegras);
            int fb = 0;
            int fn = 0;
                
            foreach (var item in Variables.fichas)
            {
                if (item.color=="blanco") {
                    fb = fb + 1;
                }

            }
            foreach (var item in Variables.fichas)
            {
                if (item.color == "negro")
                {
                    fn = fn + 1;
                }

            }

            System.Diagnostics.Debug.WriteLine("OTRO RESULTADO Fichas blancas: " + fb);
            System.Diagnostics.Debug.WriteLine("OTRO RESULTADO Fichas negras:  " + fn);

            var gan = (Proyecto_201700404.Models.USUARIO)Session["user"];
            if (fichasblancas > fichasnegras)
            {
                if (Variables.modalidad == 1) {

                    if (Variables.viene == 1)
                    {
                        ganador.ganador = "Invitado";
                    }
                    else
                    {
                        ganador.ganador = "Maquina";
                    }
                    ganador.perdedor = gan.nombreUsuario;
                    ganador.fichasGanador = fichasblancas;
                    ganador.fichasPerdedor = fichasnegras;


                    ganador.movimientosGanador = Variables.mov_jugador2;
                    ganador.movimeintoPerdedor = Variables.mov_jugador1;

                } else if (Variables.modalidad==2) {

                    if (Variables.viene == 1)
                    {
                        ganador.perdedor = "Invitado";
                    }
                    else
                    {
                        ganador.perdedor = "Maquina";
                    }
                    ganador.ganador = gan.nombreUsuario;
                    ganador.fichasGanador = fichasnegras;
                    ganador.fichasPerdedor = fichasblancas;


                    ganador.movimientosGanador = Variables.mov_jugador1;
                    ganador.movimeintoPerdedor = Variables.mov_jugador2;

                }

                //ganador.ganador = gan.nombreUsuario;
                
                //ganador.perdedor = gan.nombreUsuario; COMENTADO POR LA NUEVA MODALIDAD DE JUEGO
                //ganador.fichasGanador = fichasblancas ;
                //ganador.fichasPerdedor = fichasnegras;

                
                //ganador.movimientosGanador = Variables.mov_jugador2;
                //ganador.movimeintoPerdedor = Variables.mov_jugador1;


            }
            else if (fichasnegras > fichasblancas)
            {

                if (Variables.modalidad == 1)
                {
                    ganador.ganador = gan.nombreUsuario;
                    if (Variables.viene == 1)
                    {
                        ganador.perdedor = "Invitado";
                    }
                    else
                    {
                        ganador.perdedor = "Maquina";
                    }

                    ganador.fichasGanador = fichasnegras;
                    ganador.fichasPerdedor = fichasblancas;
                    ganador.movimientosGanador = Variables.mov_jugador1;
                    ganador.movimeintoPerdedor = Variables.mov_jugador2;


                }
                else if(Variables.modalidad==2) {

                    ganador.perdedor = gan.nombreUsuario;
                    if (Variables.viene == 1)
                    {
                        ganador.ganador = "Invitado";
                    }
                    else
                    {
                        ganador.ganador = "Maquina";
                    }

                    ganador.fichasGanador = fichasblancas;
                    ganador.fichasPerdedor = fichasnegras;
                    ganador.movimientosGanador = Variables.mov_jugador2;
                    ganador.movimeintoPerdedor = Variables.mov_jugador1;


                }

                
            }
            else if (fichasnegras==fichasblancas) {
                ganador.ganador = "Empate";
                ganador.perdedor = "Invitado";
                ganador.fichasGanador = fichasnegras;
                ganador.fichasPerdedor = fichasblancas;
                ganador.movimientosGanador = Variables.mov_jugador1;
                ganador.movimeintoPerdedor = Variables.mov_jugador2;
            }

            System.Diagnostics.Debug.WriteLine("ESTOS DATOS TRAE LA VARIABLE GANADOR fichas ganador: "+ganador.fichasGanador);
            System.Diagnostics.Debug.WriteLine("ESTOS DATOS TRAE LA VARIABLE GANADOR fichas perdedor: " + ganador.fichasPerdedor);




           Variables.ganador = ganador;

            Variables.fichas.Clear();
            Variables.VaciarTablero();



            iGamegtEntities1 bdatos = new iGamegtEntities1();

            Juego juego = new Juego();
            juego.idjugador = gan.id_usuario;
            juego.ganador = Variables.ganador.ganador;
            juego.perdedor = Variables.ganador.perdedor;
            juego.mov_ganador = Variables.ganador.movimientosGanador;
            juego.mov_perdedor = Variables.ganador.movimeintoPerdedor;
            juego.fichas_ganador = Variables.ganador.fichasGanador;
            juego.fichas_perdedor = Variables.ganador.fichasPerdedor;

            bdatos.Juego.Add(juego);
            bdatos.SaveChanges();



            return View();
        }

        public ActionResult RegresarMenu() {
            return RedirectToAction("Player","Player");
        }

Proyecto_201700404/Views/Master/CampodeJuego.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/JugarEstilos.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />

</head>
<body class="variable">
    <div style="height:100px;  background-color:rgba(5, 5, 5,.4); margin-top:40px; border-radius:5px;" class=" container">
        <div style="width:80%;  position:absolute; top:13%; left:50%; transform:translate(-47%,-50%);" class="row ">
            <div class="col text-white">
                <button style="width:200px" class=" btn btn-primary">
                    <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-cpu" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M5 0a.5.5 0 0 1 .5.5V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2A2.5 2.5 0 0 1 14 4.5h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14a2.5 2.5 0 0 1-2.5 2.5v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14A2.5 2.5 0 0 1 2 11.5H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2A2.5 2.5 0 0 1 4.5 2V.5A.5.5 0 0 1 5 0zm-.5 3A1.5 1.5 0 0 0 3 4.5v7A1.5 1.5 0 0 0 4.5 13h7a1.5 1.5 0 0 0 1.5-1.5v-7A1.5 1.5 0 0 0 11.5 3h-7zM5 6.5A1.5 1.5 0 0 1 6.5 5h3A1.5 1.5 0 0 1 11 6.5v3A1.5 1.5 0 0 1 9.5 11h-3A1.5 1.5 0 0 1 5 9.5v-3zM6.5 6a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z" />
                    </svg>@Html.ActionLink("Maquina", "ContraMaquina", "Jugar", new { area = "" }, new { @class = "text-white" })
                </button>

            </div>
            <div class="col text-white">
                <button style="width:200px" class="btn btn-primary">
                    <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-person-plus-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm7.5-3a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
                    </svg> @Html.ActionLink("Contrincante", "ConfiguracionFichas", "Jugar", new { area = "" }, new { @class = "text-white" })
                </button>

            </div>
            <div class="col text-white">
                <button style="width:200px" class="btn btn-primary">
                    <svg width="3em" height="3em" viewBox="0 0 17 16" class="bi bi-exclamation-triangle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M7.938 2.016a.146.146 0 0 0-.054.057L1.027 13.74a.176.176 0 0 0-.002.183c.016.03.037.05.054.06.015.01.034.017.066.017h13.713a.12.12 0 0 0 .066-.017.163.163 0 0 0 .055-.06.176.176 0 0 0-.003-.183L8.12 2.073a.146.146 0 0 0-.054-.057A.13.13 0 0 0 8.002 2a.13.13 0 0 0-.064.016zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z" />
                        <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z" />
                    </svg>@Html.ActionLink("Xtreme", "RegistroInvitado", "Xtreme", new { area = "" }, new { @class = "text-white" })
                </button>

            </div>
            <div class="col text-white">
                <button style="width:200px" class="btn btn-primary">
                    <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-trophy" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M2.5.5A.5.5 0 0 1 3 0h10a.5.5 0 0 1 .5.5c0 .538-.012 1.05-.034 1.536a3 3 0 1 1-1.133 5.89c-.79 1.865-1.878 2.777-2.833 3.011v2.173l1.425.356c.194.048.377.135.537.255L13.3 15.1a.5.5 0 0 1-.3.9H3a.5.5 0 0 1-.3-.9l1.838-1.379c.16-.12.343-.207.537-.255L6.5 13.11v-2.173c-.955-.234-2.043-1.146-2.833-3.012a3 3 0 1 1-1.132-5.89A33.076 33.076 0 0 1 2.5.5zm.099 2.54a2 2 0 0 0 .72 3.935c-.333-1.05-.588-2.346-.72-3.935zm10.083 3.935a2 2 0 0 0 .72-3.935c-.133 1.59-.388 2.885-.72 3.935zM3.504 1c.007.517.026 1.006.056 1.469.13 2.028.457 3.546.87 4.667C5.294 9.48 6.484 10 7 10a.5.5 0 0 1 .5.5v2.61a1 1 0 0 1-.757.97l-1.426.356a.5.5 0 0 0-.179.085L4.5 15h7l-.638-.479a.501.501 0 0 0-.18-.085l-1.425-.356a1 1 0 0 1-.757-.97V10.5A.5.5 0 0 1 9 10c.516 0 1.706-.52 2.57-2.864.413-1.12.74-2.64.87-4.667.03-.463.049-.952.056-1.469H3.504z" />
                    </svg> Torneo
                </button>

            </div>


        </div>

        @*<div style="width:60%;" class="row container  bg-primary">

                <div class="col row text-white">
                    1 de 3

                </div>
                <div class="col row text-white">
                    2 de 3

                </div>
                <div class="col row text-white">
                    3 de 3

                </div>

            </div>*@

    </div>

    @RenderBody()

</body>
</html>

Proyecto_201700404/Views/Master/MasterAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
    <link href="~/Content/MasterAdmin.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
    <div >
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-primary">
                <div class="container">
                    <a class="navbar-brand text-white " hrer="#">i GAMEGT</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link text-white" href="#">Admin <span class="sr-only">(current)</span></a>
                            </li>
                            
                        </ul>
                       
                    <form class="form-inline my-2 my-lg-0">
                        

                        <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-person-bounding-box" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z" />
                            <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                        </svg>



                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @RenderSection("encabezado",false)
                                  
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">


                                    <label class="dropdown-item  text-white text-center">@Html.ActionLink("Cerrar Sesion", "Cerrar", "Admin")</label>
                                    
                                        
                                    
                                    
                                    @*<a class="dropdown-item text-white" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item text-white" href="#">Something else here</a>*@
                                </div>
                            </li>

                        </ul>
                    </form>
                    </div>

                </div>

            </nav>
        </header>

    </div>
    <div class="variable" >
        <div class="container">
            <div class="row">
                <div class="col-2 difuminado1 principal ">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active text-white text-left" href="#">Active</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white text-left" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white text-left" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled text-white text-left" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>
                    </ul>

                </div>
                <div class="col-10 difuminado2 principal">
                    @RenderBody()

                </div>


            </div>

        </div>

        
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Proyecto_201700404/Views/Master/MasterPlayer.cshtml
@model Proyecto_201700404.Models.USUARIO
@{ 
    var user = (Proyecto_201700404.Models.USUARIO)Session["user"];

}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Game</title>
    <link href="~/Content/Playerstyle.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
    <div>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-primary">
                <div class="container">
                    <a class="navbar-brand text-white " hrer="#">i GAMEGT</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active ">

                                

                                    @Html.ActionLink("Mis Datos", "Player", "Player", new { area=""}, new { @class = " text-white" })
                             
                                


                            </li>
                        
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Partidas
                                </a>
                                <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdown">

                                    <label class="dropdown-item text-center bg-primary">
                                        @Html.ActionLink("Cargar", "Archivo", "Archivo",null, new { @class = "text-white" })
                                    </label>
                                    <label class="dropdown-item text-center bg-primary">
                                        @Html.ActionLink("Nueva Partida", "Jugar", "Jugar", null, new { @class = "text-white" })
                                    </label>


                                </div>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link active text-white" href="#" tabindex="-1" aria-disabled="true">Torneos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active text-white" href="#" tabindex="-1" aria-disabled="true">@Html.ActionLink("Estadisticas", "Estadisticas", "Player", new { area = "" }, new { @class = " text-white" })</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active text-white" href="#" tabindex="-1" aria-disabled="true">fecha del sistema 00/00/0000</a>
                            </li>
                        </ul>




                        <form class="form-inline my-2 my-lg-0">


                            <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-person-bounding-box" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z" />
                                <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                            </svg>



                            <ul class="navbar-nav mr-auto ">
                                <li class="nav-item dropdown ">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @try
                                        {
                                            if (user == null) { }
                                            else
                                            {
                                                <label class="text-white">@user.nombre @user.apellido</label>

                                            }
                                        }
                                        catch (Exception)
                                        {

                                            throw;
                                        }

                                    </a>
                                    <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdown">


                                        <label class="dropdown-item text-center bg-primary">@Html.ActionLink("Cerrar Sesion", "Cerrar", "Admin",null,new { @class="text-white"})</label>




                                        @*<a class="dropdown-item text-white" href="#">Another action</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item text-white" href="#">Something else here</a>*@
                                    </div>
                                </li>

                            </ul>
                        </form>





                    </div>

                </div>

            </nav>

        </header>

    </div>


    <div class="variable">
        @RenderBody()
       

    @*@RenderSection()

        @RenderPage(path)*@
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Proyecto_201700404/Views/Master/MasterTablero.cshtml
@{
    Layout = null;
}